AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'mktanon site'

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  RobinReaderCsvUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jsat-robin-reader-csv-upload
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - PUT
            AllowedHeaders:
              - "*"

  MktAnonSiteFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3UploadAndGetAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub arn:aws:s3:::jsat-robin-reader-csv-upload/*
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub arn:aws:s3:::jsat-robin-reader-csv-upload/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "POST"
        AllowHeaders:
          - "*"
        
  UploadCsvFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: robinReader/package
      Handler: uploadCsvFunction.lambda_handler
      Runtime: python3.10
      Environment:
        Variables:
          BUCKET_NAME: jsat-robin-reader-csv-upload
      Role: !GetAtt MktAnonSiteFunctionRole.Arn
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref RobinReaderCsvUploadBucket
      Events:
        UploadCsvApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /upload
            Method: post

  # UploadFunctionasdfs:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: robinReader/package/
  #     Handler: app.lambda_handler
  #     Role: !GetAtt MktAnonSiteFunctionRole.Arn
  #     Runtime: python3.10
  #     Architectures:
  #       - x86_64
  #     Layers:
  #       - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-pandas:13
  #     Events:
  #       ApiCall:
  #         Type: HttpApi 
  #         Properties:
  #           Path: /uploadsdf
  #           Method: post

Outputs:
  ApiEndpoint:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
       
