AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'mktanon site'

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  MktAnonSiteFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  MktAnonApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "https://mktanon.com"
          - "http://127.0.0.1:5506"
        AllowMethods:
          - "POST"
        AllowHeaders:
          - "*"
        
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: robinReader/package
      Handler: createFunction.lambda_handler
      Runtime: python3.10
      Layers:
        - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-pandas:13
      Role: !GetAtt MktAnonSiteFunctionRole.Arn
      Events:
        UploadCsvApiCalled:
          Type: HttpApi
          Properties:
            ApiId: !Ref MktAnonApi
            Path: /create
            Method: post

Outputs:
  UploadCsvApiEndpoint:
    Description: "API endpoint URL for uploading CSV"
    Value: !Sub "https://${MktAnonApi}.execute-api.${AWS::Region}.amazonaws.com/create"
  
